### ISSUE TITLE
We did something wrong?

### ISSUE THREAD

**Issue by PennyJim** [dima74/factorio-mods-localization#19]
Based on my understanding, https://github.com/MrSmoothieHuman1/pirate-locale should work.

I don't know what I did wrong with the 'multimod repository,' but my refactor over on https://github.com/PennyJim/pirate-locale works.

Just for future reference, I would like to understand what may have gone wrong. Admittedly, the person who went ahead and created the repository is a git newbie and may have done something incorrect when adding the app.

**Comment by PennyJim** [comment]
I also want to ask if you'd be interested in adding joke languages to the Crowdin. You'd have to do some pre-processing to make it work natively in Factorio (like replace english or inject an info.json into the core files), but that way our appropriating French for our purposes wouldn't be doing 'helpful' things like providing translations from identical strings.

It may not be the worst because we can overwrite it, but it does hamper keeping track of what we need to 'translate.'

That might just be a wild misappropriation of this app though and maybe you can help me setup a fork so I don't 'spoil' the core crowdin.

**Comment by dima74** [comment]
Hi!

It didn't work for https://github.com/MrSmoothieHuman1/pirate-locale because of a small typo in the config file name, it is expected to be `factorio-mods-localization.json`.

---

Regarding joke languages, to be honest I don't understand how it is expected to work (especially when using translation mod in Factorio - is it allowed to overwrite core Factorio strings?), but I have some idea how it can work on Crowdin - it is possible [to select languages for each file](https://github.com/dima74/factorio-mods-localization/assets/6505554/e5f9af6e-295b-4a16-89f5-b3eaddc71cbe). So in the case of `pirate-locale` I can select only French (by the way maybe select some other language not so popular to avoid confusion?). So someone will not accidentally translate the whole Factorio strings.

**Comment by PennyJim** [comment]
> because of a small type in the config file name

I really should've looked at that closer..

----
If there's a duplicate localization key, the last one processed will overwrite the previous keys. Meaning mods can overwrite core localization, or even the localization of another mod.

For our mod purposes, we'll just do some pre-processing before zipping it. So we'll take any arbituary folder that the 'translated' strings are in, and replace the source english with it.

Factorio also will accept any arbitrary folder as a language. The only thing required to make it actually function, is a info.json in the core files, but there's no issues without it. Is there a chance this app will support additional languages, maybe with a warning that they won't natively do anything? Maybe a setting you can set to specifically enable specific crowdin languages so they aren't available by default?

**Comment by dima74** [comment]
> Is there a chance this app will support additional languages, maybe with a warning that they won't natively do anything? Maybe a setting you can set to specifically enable specific crowdin languages so they aren't available by default?

In theory it is possible to implement, but most likely I will not have time for it in the near future.

I think there is a problem with the current setup because it might be not clear that only French should be "translated", and there are already some translations for other languages. For now I selected only French language for all files in `Pirate Locale (PennyJim)`, so hopefully this will reduce confusion for translators

**Comment by dima74** [comment]
@PennyJim Hi! I noticed app was uninstalled for https://github.com/PennyJim/pirate-locale. Please let me know should I remove it from Crowdin? Thank you.

**Comment by PennyJim** [comment]
Go ahead. There was a lot of initial energy, and it just kinda never went anywhere ¯\⁠\_⁠(⁠ツ⁠)⁠\_⁠/⁠¯
